# Generated by Django 4.1 on 2024-12-07 19:06

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=150, null=True)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('featured_picture', models.ImageField(blank=True, null=True, upload_to=shop.models.get_cat_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/user/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('wait_for_pay', 'Wait for Pay'), ('complete', 'Complete'), ('wait_for_review', 'Wait for review')], default='pending', max_length=100)),
                ('need_tracking', models.BooleanField(default=False)),
                ('tracking_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('downloadable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('product_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('featured_picture', models.ImageField(blank=True, null=True, upload_to=shop.models.get_pro_upload_path)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Telebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('token', models.CharField(max_length=300, verbose_name='توکن')),
                ('welcome_message', models.TextField(verbose_name='پیام خوش آمدگویی')),
                ('welcome_picture', models.ImageField(upload_to='media/pictures/', verbose_name='تصویر خوش آمدگویی')),
                ('select_category_message', models.CharField(default='لطفا دسته بندی را انتخاب کنید', max_length=300)),
                ('back_button_text', models.CharField(default='بازگشت', max_length=150)),
                ('select_product_message', models.CharField(default='محصول را از لیست زیر انتخاب کنید', max_length=300)),
                ('no_product_message', models.CharField(default='مصحولی در این دسته بندی وجود ندارد', max_length=300)),
                ('product_stock_message', models.CharField(default='متاسفانه موجودی این محصول به پایان رسید', max_length=300)),
                ('card_number_text', models.CharField(default='5041721025446205', max_length=16)),
                ('category_button_text', models.CharField(default='دسته بندی ها 📁', max_length=150)),
                ('basket_button_text', models.CharField(default='سبد خرید 🛍️', max_length=150)),
                ('order_button_text', models.CharField(default='سفارشات من 📦', max_length=150)),
                ('send_recipe_button_text', models.CharField(default='ارسال رسید خرید', max_length=150)),
                ('cancel_button_text', models.CharField(default='لغو سفارش', max_length=150)),
                ('cancel_order_message', models.CharField(default='سفارش شما لغو شد', max_length=300)),
            ],
            options={
                'verbose_name': 'ربات',
                'verbose_name_plural': 'ربات ها',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('current_order_id', models.IntegerField(default=0)),
                ('last_message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_order_message_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop.models.get_pro_image_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.telegramuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.address'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.telegramuser'),
        ),
    ]
